
[project]
dependencies = ["opencv-python==4.5.3.56", "numpy==1.21.5", "scikit-image>=0.19.3", "matplotlib==3.5.1", "torch==1.13.1", "grad-cam==1.4.6", "fastAPI>=0.103.2"]
requires-python = "<3.11,>=3.7"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
